CREATE TABLE IG_DEPENDANT_FIELDS 
(
  IGDF_ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL 
, IGDF_NEEDS_ATTENTION VARCHAR2(1) NOT NULL 
, IGDF_REMARK VARCHAR2(4000) 
, IGDF_ACTION VARCHAR2(4000)
);

alter table ig_dependant_fields
  add CONSTRAINT IGDF_PK PRIMARY KEY(IGDF_ID)
;

ALTER TABLE IG_DEPENDANT_FIELDS
ADD CONSTRAINT IGDF_COMBINATIONS_CK CHECK 
(( igdf_needs_attention = 'Y' and igdf_remark is not null and igdf_action is not null ) or
igdf_needs_attention = 'N')
ENABLE;

ALTER TABLE IG_DEPENDANT_FIELDS
ADD CONSTRAINT IGDF_NEEDS_ATTENTION_CK CHECK 
(igdf_needs_attention in ('Y', 'N'))
ENABLE;
